### ISSUE TITLE
No such thing as commit.author.login

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/javascript-xhr#11]
Error: 
** **

Context: 
`function showCommits() {
  const commits = JSON.parse(this.responseText)
  const commitsList = `<ul>${commits.map(commit => '<li><strong>' + commit.commit.author.name + '</strong> - ' + commit.commit.message + '</li>').join('')}</ul>`
  document.getElementById("commits").innerHTML = commitsList
}`

Looking at the array of objects returned by the Github API there is no such thing as commit.author.login in the returned hash. However, there is a commit.commit.author.name. Is this what you mean?
This worked >> commit.commit.author.name + '</strong> - ' + commit.commit.message

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
