### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/javascript-xhr#5]
index-test.js:44
    let xhr
    ^^^

Needs "use strict"; on line 44.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
