### ISSUE TITLE
GitHub API now on v4 using GraphQL

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/javascript-xhr#6]
While this will not affect anything for some time GitHub released v4 of their API and it utilizes GraphQL. This should be taken into account and the lesson updated before it completely stops working in the future. If deprecating API versions is such a thing.

**Comment by gj** [comment]
Hi @itzsaga !

Normally it is a thing, but GitHub's taken steps to ensure that it won't be here. Thanks though!
